name    'erwbgy-pdns'
version '0.0.1'
author 'Keith Burdis'
license 'Apache License, Version 2.0'
summary 'PowerDNS nameserver or resolver'
description 'Installs and configures a PowerDNS nameserver or resolver'
project_page 'https://github.com/erwbgy/puppet-pdns'
