name    'erwbgy-pdns'
version '0.3.2'
author 'Keith Burdis'
license 'Apache License, Version 2.0'
summary 'PowerDNS nameserver or resolver'
description 'Installs and configures a PowerDNS nameserver or resolver, with support for running internal domains'
project_page 'https://github.com/erwbgy/puppet-pdns'
